<a href="https://colab.research.google.com/github/roshkjr/DeepLearning/blob/main/pytorch%20fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

This is the first notebook from the series of notebooks I am planning to create as part of my learning path for deep learning. If you are also new to Pytorch just like me, hope you find this useful, and if you did, please express you appreciation by giving a star to my github repository and sharing these notebooks 🙏

Pytorch is a popular framework in Python for training and building deep learning models, open-sourced by Meta. I will be discussing some fundamental concepts in Pytorch including data represenation and operations using Tensors in this notebook. So without any further delay, let's get started 🤩

## Tensors

If you have never heard the word Deep Learning before, what would you guess it means? If you guessed it is about Learning, then you guessed it right. It is a method for computers to learn patterns from data. In order to make computers learn from data, the data need to be represented and processed efficiently. Tensors are data structures designed to store and process data for developing deep learning models in Pytorch. Tensors are a lot similar to ndarrays in Numpy, but with two superpowers 💪:
1. Support for automatic differentiation
2. Support for GPU accelerated numerical calculations

We will discuss what these features means, and why they are important. But before that, let's get some hands-on with Tensors and see what can they do 🚀

In [1]:
import torch

## Creating Tensors

PyTorch provides different fucntions to create tensors populated with values. In this section we will look into some of these functions.

In [6]:
# creating a tensor with evenly spaced values
n = 10
x = torch.arange(n)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


arange creates an evenly spaced vector of values starting from 0 and ending in n (not included). The default data type for arange is 64-bit integer

In [10]:
# creating a tensor with non-zero start and custom step value
x = torch.arange(start=5, end=20, step=5)
x

tensor([ 5, 10, 15])

In [11]:
x.dtype

torch.int64

In [13]:
# creating tensor with float data type
x = torch.arange(5, dtype=torch.float32)
x.dtype

torch.float32

In [14]:
# finding the number of elements
x.numel()

5

The dimensions of a tensor can be accessed using the shape attribute, and it can be altered to a compatible alternatives using reshape method.

In [15]:
x.shape

torch.Size([5])

In [16]:
# changing the dimensions of a tensor
x = torch.arange(12).reshape((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

For any 2D tensor, num_ele = num_rows * num_col. Hence, one of the dimensions of reshaped tensor can be implicitly calculated, given all other dimensions.

In [18]:
# reshaping tensor using implicit dimension
torch.arange(12).reshape((4,-1))

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

While developing deep learning models, the parameters of the model are often initialized randomly. You can generate a random tensor from a standard normal distribution (mean = 0, standard deviation = 1) using torch.randn

In [25]:
# creating a random tensor
x = torch.randn(3,4)
x

tensor([[ 1.5969, -0.2940,  0.9667, -0.1470],
        [ 0.0844, -0.7506,  1.2532, -0.6951],
        [ 0.2990,  1.8869, -0.0500,  0.0776]])

In [19]:
# creating tensor with zeros
zero = torch.zeros((4,5))
zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [20]:
# creating tensor with ones
ones = torch.ones((2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
# creating a tensor with zeros with the same shape of another tensor
y = torch.zeros_like(ones)
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:
# creating a tensor from a list of values
x = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[10,11,12],
                   [13,14,15],
                   [16,17,18]]])
x.shape

torch.Size([2, 3, 3])

The shape of a tensor is read from outer to inner paratheses. In the above example, there are two brackets inside the first bracket, hence the first dimension is 2. Similarly the second and third dimensions are 3, each corresponding to 3 brackets with second and third brackets from the outer 😵. The best way to check your understanding of tensor dimensions is to access different slices of the tensor and see if are getting it right. Let's try some examples together.

In [34]:
# get the number 5 from the above tensor
x[0,1,1]

tensor(5)

In [35]:
# get the row [7,8,9] from the above tensor
x[0,2,:]

tensor([7, 8, 9])

In [36]:
# get the row [13,14,15] from the above tensor
x[1,1,:]

tensor([13, 14, 15])